### ISSUE TITLE
Wrong TradeItOrderPriceType

### ISSUE THREAD

**Issue by Blackramon** [tradingticket/AndroidSDK#111]
https://github.com/tradingticket/AndroidSDK/blob/develop/tradeit-android-sdk/src/main/kotlin/it/trade/android/sdk/enums/TradeItOrderPriceType.kt

PriceTypeValue of TradeItOrderPriceType is wrong for STOP_MARKET and STOP_LIMIT. So it make display value of this TradeItOrderPriceTypeParcelable class is wrong also. Could anyone help to check?

**Comment by guillaumedebavelaere** [comment]
Fixed in 1.0.30
